// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Info Code Smell", "S1135:Track uses of \"TODO\" tags", Justification = "<Pending>", Scope = "member", Target = "~M:OMega.Lib.DbContexts.CompanyDbContainer.DbContextHelper.UpdateDataAsync``1(``0,System.Boolean,System.String,System.Boolean)~System.Threading.Tasks.Task{System.Int32}")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:FrontLook.IAutoHistory.DbContexts.DbContextHelper.OnModelCreating(Microsoft.EntityFrameworkCore.ModelBuilder)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:FrontLook.IAutoHistory.DbContexts.DbContextHelper.DetachAllEntities")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:FrontLook.IAutoHistory.DbContexts.DbContextHelper.SaveData``1(``0,System.Boolean,System.String,System.Boolean)~System.Int32")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:FrontLook.IAutoHistory.DbContexts.DbContextHelper.SaveDataAsync``1(``0,System.Boolean,System.String,System.Boolean)~System.Threading.Tasks.Task{System.Int32}")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:FrontLook.IAutoHistory.DbContexts.DbContextHelper.SaveDataRange``1(System.Collections.Generic.List{``0},System.Boolean,System.String,System.Boolean)~System.Int32")]
[assembly: SuppressMessage("Minor Code Smell", "S3220:Method calls should not resolve ambiguously to overloads with \"params\"", Justification = "<Pending>", Scope = "member", Target = "~M:FrontLook.IAutoHistory.DbContexts.DbContextHelper.SaveDataRangeAsync``1(``0,System.Boolean,System.String,System.Boolean)~System.Threading.Tasks.Task{System.Int32}")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:FrontLook.IAutoHistory.DbContexts.DbContextHelper.SaveDataRangeAsync``1(``0,System.Boolean,System.String,System.Boolean)~System.Threading.Tasks.Task{System.Int32}")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:FrontLook.IAutoHistory.DbContexts.DbContextHelper.UpdateDataAsync``1(``0,System.Boolean,System.String,System.Boolean)~System.Threading.Tasks.Task{System.Int32}")]
[assembly: SuppressMessage("Info Code Smell", "S1135:Track uses of \"TODO\" tags", Justification = "<Pending>", Scope = "member", Target = "~M:FrontLook.IAutoHistory.DbContexts.DbContextHelper.UpdateDataAsync``1(``0,System.Boolean,System.String,System.Boolean)~System.Threading.Tasks.Task{System.Int32}")]
[assembly: SuppressMessage("Minor Code Smell", "S1481:Unused local variables should be removed", Justification = "<Pending>", Scope = "member", Target = "~M:FrontLook.IAutoHistory.DbContexts.DbContextHelper.UpdateDataRangeAsync``1(System.Collections.Generic.List{``0},System.Boolean,System.String,System.Boolean)~System.Threading.Tasks.Task{System.Collections.Generic.List{System.Int32}}")]
[assembly: SuppressMessage("Minor Code Smell", "S1481:Unused local variables should be removed", Justification = "<Pending>", Scope = "member", Target = "~M:FrontLook.IAutoHistory.DbContexts.DbContextHelper.UpdateDataAsync``1(``0,System.Boolean,System.String,System.Boolean)~System.Threading.Tasks.Task{System.Int32}")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:FrontLook.IAutoHistory.DbContexts.DbContextHelper.UpdateDataRangeAsync``1(System.Collections.Generic.List{``0},System.Boolean,System.String,System.Boolean)~System.Threading.Tasks.Task{System.Collections.Generic.List{System.Int32}}")]
